Medium api
ms-club-sliit/msclubwebsite pull request #104
Opened 2021-08-05 08:50 UTC by MadhushaPrasad

2021-08-05 13:30 UTC, senuravihanjayadeva requested changes

2021-08-05 13:30 UTC, senuravihanjayadeva commented on src/modules/BlogModules/BlogList/BlogList.jsx
> +    axios.get('https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@dckalubowila25132')
You got the blogs from Dinuwan Ayyas medium account.
Not from Ms Club Publication.

2021-08-06 02:28 UTC, senuravihanjayadeva commented on src/modules/BlogModules/BlogList/BlogList.jsx
> +    axios.get('https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@dckalubowila25132')
And I think using rss feed we can get only 10 posts. isnt it ? @DInuwan97 @rusiruavb @dcjc29 @Shehanka

2021-08-12 14:33 UTC, MadhushaPrasad reviewed
done

2021-08-12 18:40 UTC, closed without merging