Create new branch to add About Us section
ms-club-sliit/msclubwebsite pull request #23
Opened 2021-04-07 08:00 UTC by rusiruavb

2021-04-07 14:03 UTC, DInuwan97 approved these changes

2021-04-07 14:05 UTC, DInuwan97 approved these changes

2021-04-07 14:54 UTC, Shehanka requested changes

2021-04-07 14:54 UTC, Shehanka commented on src/pages/AboutUsPage/WhatWeDoSection/WhatWeDoSection.js
> +  )
move all About Us sub-components to modules/AboutUs/WhatWeDoSection
Only AboutUs.jsx should be here.

2021-04-07 15:14 UTC, rusiruavb commented on src/pages/AboutUsPage/WhatWeDoSection/WhatWeDoSection.js
> +  )
Ok. I will do the modification

2021-04-07 15:38 UTC, rusiruavb commented on src/pages/AboutUsPage/WhatWeDoSection/WhatWeDoSection.js
> +  )
@Shehanka I have moved about us sub-components to the modules folder.

2021-04-07 15:42 UTC, gihanrcg commented on src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.js
> +          <div className='col-md-3 mb-3'>
Can we extract this to a new functional component?
@Shehanka @Bawanthathilan

2021-04-07 15:46 UTC, gihanrcg commented
@rusiruavb @Shehanka  Is there a reason for us to working with  `.js` instead of `.jsx` ???

2021-04-07 15:47 UTC, Shehanka commented
> @rusiruavb @Shehanka Is there a reason for us to working with `.js` instead of `.jsx` ???

I also gonna ask it.

2021-04-07 15:49 UTC, Shehanka commented on src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.js
> +          <div className='col-md-3 mb-3'>
@gihanrcg yeah! that would be great. 
@rusiruavb also remove unused index variable

2021-04-07 15:50 UTC, Shehanka commented
@nisalrenuja, @dcjc29 can u set up husky, eslint stuff. If you guys are busy share that recorded video.

2021-04-07 15:54 UTC, gihanrcg reviewed
> @nisalrenuja, @dcjc29 can u set up husky, eslint stuff. If you guys are busy share that recorded video.

Added a separate issue for this

2021-04-07 15:54 UTC, gihanrcg commented on src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.json
> +{
This is mock data,, isn't it ?

2021-04-07 15:54 UTC, gihanrcg commented on src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.css
> +  background: white;
Let's use variables for these colors. It will be easier to implement the dark mode I guess

2021-04-07 15:55 UTC, Shehanka commented
> > @nisalrenuja, @dcjc29 can u set up husky, eslint stuff. If you guys are busy share that recorded video.
> 
> Added a separate issue for this

sure

2021-04-07 15:55 UTC, gihanrcg commented on src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.js
> +          <div className='col-md-3 mb-3'>
else use the index as a key in the div

`<div key={index} >`

2021-04-07 15:56 UTC, rusiruavb commented on src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.js
> +          <div className='col-md-3 mb-3'>
I will do the chage

2021-04-07 16:04 UTC, rusiruavb commented on src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.json
> +{
Yes

2021-04-07 18:39 UTC, rusiruavb commented on src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.css
> +  background: white;
Okay, I will assign colors into variables.  Is this kind of naming convention is good for variables?
for light mode:
`:root {
  --light-icon-color: #2cb93b;
  --white: #ffffff;
  --light-shadow-color: #6ec476;
}`

for dark mode:
`:root {
  --dark-icon-color: #2cb93b;
  --white: #ffffff;
  --dark-shadow-color: #6ec476;
}`

2021-04-08 05:02 UTC, Shehanka commented on src/pages/AboutUsPage/WhatWeDoSection/WhatWeDoSection.js
> +  )
@rusiruavb thanks

2021-04-08 05:04 UTC, gihanrcg commented on src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.css
> +  background: white;
yp. looks great

2021-04-08 08:21 UTC, closed without merging