Footer #9 finished
ms-club-sliit/msclubwebsite pull request #26
Opened 2021-04-08 02:37 UTC by MadhushaPrasad

2021-04-08 03:19 UTC, gihanrcg commented on src/component/common/footer/Footer.css
> +    background-color: #1F1F22;
Why don't we use colors as css variables ?

2021-04-08 03:23 UTC, gihanrcg reviewed
- Use variables instead of hardcoded colors in CSS
- Use stateless functional components instead of class components 

@Shehanka @dcjc29 @DInuwan97 @ms-club-sliit/dev-team  Please comment your concerns here

2021-04-08 03:23 UTC, gihanrcg commented on src/component/common/footer/Footer.js
> +import React, {Component} from 'react';
Shall we use stateless functions instead of classes?
@Shehanka @dcjc29 @DInuwan97  isn't it the industry practice right now ???

2021-04-08 05:04 UTC, Shehanka commented on src/component/common/footer/Footer.js
> +import React, {Component} from 'react';
yes.

2021-04-08 05:07 UTC, Shehanka requested changes

2021-04-08 05:07 UTC, Shehanka commented on .eslintcache
> +[{"D:\\MS_Club\\msclubwebsite\\src\\index.js":"1","D:\\MS_Club\\msclubwebsite\\src\\App.js":"2","D:\\MS_Club\\msclubwebsite\\src\\reportWebVitals.js":"3","D:\\MS_Club\\msclubwebsite\\src\\pages\\Abou
@MadhushaPrasad gitignore cache

2021-04-08 05:07 UTC, Shehanka commented on .eslintcache
> +[{"D:\\MS_Club\\msclubwebsite\\src\\index.js":"1","D:\\MS_Club\\msclubwebsite\\src\\App.js":"2","D:\\MS_Club\\msclubwebsite\\src\\reportWebVitals.js":"3","D:\\MS_Club\\msclubwebsite\\src\\pages\\Abou
and remove it from git cache
```
git rm -rf --cached .eslintcached
```

2021-04-08 05:07 UTC, Shehanka commented on src/App.js
make this functional component

2021-04-09 08:06 UTC, gihanrcg commented on src/component/common/footer/Footer.js
> +          <h5>Use Full Links</h5>
Useful is one word

2021-04-09 08:07 UTC, gihanrcg requested changes

2021-04-09 08:07 UTC, gihanrcg commented on src/component/common/footer/Footer.js
> +              <li className="nav-link">Code of Contact</li>
This is either **code of conduct** or **Contact Us**

2021-04-09 09:40 UTC, MadhushaPrasad commented on src/component/common/footer/Footer.js
> +              <li className="nav-link">Code of Contact</li>
Design has like this,i think it is contact us,i will change it as contact us

2021-04-11 08:30 UTC, gihanrcg submitted a review, later dismissed

2021-04-11 13:18 UTC, MadhushaPrasad commented on src/component/common/footer/Footer.js
> +import React, {Component} from 'react';
I change it and push to footer brach

2021-04-11 14:27 UTC, gihanrcg approved these changes

2021-04-12 05:54 UTC, gihanrcg approved these changes

2021-04-12 05:54 UTC, merged