Feature/about us hero section
ms-club-sliit/msclubwebsite pull request #29
Opened 2021-04-08 08:52 UTC by rusiruavb

1. Get a pull from the upstream's main branch
2. Add colors into variables.

2021-04-08 09:30 UTC, gihanrcg commented on src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.js
> +        <div className="col-md-3 mb-3" key={item.id}>
extract a new component from this div. use the same file :)

2021-04-08 09:32 UTC, gihanrcg commented
Great work @rusiruavb.
Can we refactor the file extention ??? from `.js` to `.jsx` ?

2021-04-08 09:33 UTC, rusiruavb commented on src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.js
> +        <div className="col-md-3 mb-3" key={item.id}>
Tou mean a sperate component to display the card?

2021-04-08 09:35 UTC, rusiruavb commented
> Great work @rusiruavb.
> Can we refactor the file extention ??? from `.js` to `.jsx` ?

Okay, I will change the extention.

2021-04-08 09:36 UTC, gihanrcg commented on src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.js
> +        <div className="col-md-3 mb-3" key={item.id}>
```
const card = (item) => {
    <div className="col-md-3 mb-3" key={item.id}>
      ....
    </div>
}
```

2021-04-08 10:07 UTC, rusiruavb commented on src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.js
> +        <div className="col-md-3 mb-3" key={item.id}>
Okay, I will do the change

2021-04-08 11:32 UTC, Shehanka requested changes

2021-04-08 11:32 UTC, Shehanka commented on src/modules/AboutUsModules/AboutUsHeroSection/HeroSection.js
> +        </div>
.jsx

2021-04-08 11:32 UTC, Shehanka commented on src/routes/AppRoutes.js
> +export default AppRoutes;
.jsx

2021-04-08 12:21 UTC, rusiruavb commented on src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.js
> +        <div className="col-md-3 mb-3" key={item.id}>
@gihanrcg I have created seperate component for display cards.

2021-04-08 12:21 UTC, rusiruavb commented on src/routes/AppRoutes.js
> +export default AppRoutes;
Okay, I will changed it

2021-04-09 15:54 UTC, rusiruavb commented
1. Change .js files to .jsx

2021-04-09 16:02 UTC, rusiruavb commented on src/routes/AppRoutes.js
> +export default AppRoutes;
@Shehanka Now I change the js files into jsx.

2021-04-11 04:39 UTC, Shehanka approved these changes

2021-04-11 04:39 UTC, merged