Speaker UI enhancement
ms-club-sliit/msclubwebsite pull request #65
Opened 2021-07-06 14:50 UTC by himashatw

Changes

- redesigned the Speakers Card
- nested JSON object added for social media links

2021-07-07 15:34 UTC, gihanrcg requested changes

2021-07-07 15:34 UTC, gihanrcg commented on src/component/TopSpeakerCard/TopSpeakerCard.jsx
> +        <img src={image} alt="speakerIMG" height="100px" width="100px" />
Can we move height and width to css ?

2021-07-07 15:45 UTC, himashatw commented on src/component/TopSpeakerCard/TopSpeakerCard.jsx
> +        <img src={image} alt="speakerIMG" height="100px" width="100px" />
Okay ill change it

2021-07-12 12:37 UTC, gihanrcg approved these changes

2021-07-12 12:37 UTC, merged